//
//  APIKeys.swift
//  Pave
//
//  Created by Rishabh on 13/08/21.
//

import Foundation

enum APIKeys: String {
    
    case firstName = "first_name"
    case lastName = "last_name"
    case dateOfBirth = "date_of_birth"
    case city = "city"
    case state = "state"
    case email = "email"
    case password = "password"
    case stockOwned = "stock_owned"
    case moneyToInvest = "money_to_invest"
    case investorType = "investor_type"
    case investmentType = "investment_type"
    case industryExcludeList = "industry_exclude_list"
    case sectorExcludeList = "sector_exclude_list"
    case code = "code"
    case message = "message"
    case data = "data"
    case userId = "user_id"
    case isActive = "is_active"
    case isDeleted = "is_deleted"
    case isBlocked = "is_blocked"
    case createdAt = "created_at"
    case updatedAt = "updated_at"
    case sessionId = "session_id"
    case token = "token"
    case user = "user"
    case userConvertedId = "user_id_converted"
    case receipt = "receipt"
    case locale = "locale"
    case price = "price"
    case isSubscribed = "is_subscribed"
    case subscribedTill = "subscribed_till"
    case productId = "product_id"
    case expiresDate = "expires_date"
    case  planValue = "plan_value"
    case isMonthCompleted = "is_month_completed"
    case isUpdatesCompleted = "is_updates_completed"
    case versusReturn = "versus_return"
    case stocksOwnedValue = "stocks_owned_value"
    case stocksOwned = "stocks_owned"
    case supportedStocks = "supported_stocks"
    case unsupportedStocks = "unsupported_stocks"
    case plaidItemId = "plaid_item_id"
    case brokerName = "broker_name"
    case plaidUserId = "plaid_user_id"
    case plaidAccessToken = "plaid_access_token"
    case myPortfolio = "my_portfolio"
    case myPortfolioSize = "my_portfolio_size"
    case stocksOwnedPlanValue = "stocks_owned_plan_value"
    case stocksOwnedChangeValue = "stocks_owned_change_value"
    case stocksOwnedChangePercentage = "stocks_owned_change_percentage"
    case cashFlow = "cash_flow"
    case totalPortfolioValue = "total_portfolio_value"
    case profileStatus = "profile_status"
    
    
    
    //Get Industries API Key
    case sectorName = "sector_name"
    case sectorId = "sector_id"
    case industriesList = "industries_list"
    case industryName = "industry_name"
    case industryId = "industry_id"
    case sectorList = "sectorlist"
    case industryCode = "industry_code"
    case sectorCode = "sector_code"

    case country = "country"
    case waitlistType = "waitlist_type"
    
    case name = "name"
    case query = "query"
    
    case stockId = "stock_id"
    case companyName = "company_name"
    case companySymbol = "company_symbol"
    case gicsIndsName = "gics_inds_name"
    case gicsSectorName = "gics_sector_name"
    case stockHolds = "stockHolds"
    case willingToSellPercent = "willingToSellPercent"
    case id = "id"
    case type = "type"
    case quantity = "quantity"
    case percentageToSell = "percentage_to_sell"
    case auth = "auth"
    case oldPassword = "old_password"
    case newPassword = "new_password"
    case confirmPassword = "confirm_password"
    case symbol = "symbol"
    case willingToSellValue = "willing_to_sell_value"
    case willingToKeepValue = "willing_to_keep_value"
    case stockDetails = "stock_details"
    case entityType = "entity_type"
    
    // Stock Details
    case date = "date"
    case stockClose = "4. close"
    case historicalData = "historicalData"
    case stockPrice = "05. price"
    case stockPercentage = "10. change percent"
    case stockChange = "09. change"
    case description = "Description"
    case Industry = "Industry"
    case Sector = "Sector"
    case overview = "overview"
    case stockAdjustedClose = "5. adjusted close"
    case value = "value"
    
    //My Plan
    case weight = "weight"
    case recommendedPlanId = "recommended_plan_id"
    case logo = "logo"
    case noOfShares = "no_of_shares"
    case amount = "amount"
    case recommendedPlan = "recommended_plan"
    case allocations = "allocations"
    case statisticsData = "statistics_data"
    case leaveInCash = "leave_in_cash"
    case cash = "cash"
    case myPlan = "my_plan"
    case updates = "updates"
    case statisticsDataId = "statistics_data_id"
    case benchmarkScore = "benchmark_score"
    case currentRisk = "current_risk"
    case initialRisk = "initial_risk"
    case newScoreOverRisk = "new_score_over_risk"
    case oldScoreOverRisk = "old_score_over_risk"
    case portfolioScore = "portfolio_score"
    case allocation = "allocation"
    case banchmarkName = "benchmark_name"
    case changePercentage = "change_percentage"
    case changeValue = "change_value"
    case negativeReturnStocks = "negative_return_stocks"
    case negativeStocksCount = "negative_stocks_count"
    case totalStockCount = "supported_stocks_count"
    case isReplaced = "is_replaced"
    case isNegativeReturn = "is_negative_return"
    case stockOwnId = "stockown_id"
    case negativeReturnAssets = "negative_return_assets"
    
    case benchmarkReturn = "Benchmark_return"
    case currentPortfolioRisk = "Current_portfolio_risk"
    case startingPortfolioReturn = "Starting_portfolio_return"
    case startingPortfolioRisk = "Starting_portfolio_risk"
    case currentPortfolioReturn = "Current_portfolio_return"
    case benchmarkRisk = "Benchmark_risk"
    case statistics = "statistics"
    case primaryPortfolioStatistics = "primary_portfolio_statistics"
    
    //Update
    case myPlanDate = "my_plan_date"
    case industry = "industry"
    case sector = "sector"
    case planId = "plan_id"
    case isUpdated = "is_updated"
    case updateId = "update_id"
    case updatesHistory = "updates_history"
    case history = "history"
    case myPlanSize = "my_plan_size"
    case isAllUpdates = "is_all_updates"
    case updateIds = "update_ids"
    
    //App Notification Setting
    case appNotification = "app_notification"
    case emailContent = "email_content"
    case monthlyPlanUpdates = "monthly_plan_updates"
    case endOfMonthCommentary = "end_of_month_commentary"
    case weeklyNewsletter = "weekly_newsletter"
    case marketResearch = "market_research"
    
    
    //Inbox
    case url = "url"
    case title = "title"
    case notificationsData = "notifications_data"
    case description_s = "description"
    case page = "page"
    case limit = "limit"
    case search = "search"
    case nextPage = "nextPage"
    case count = "count"
    case adminNotificationId = "admin_notification_id"
    case alert = "alert"
    case payload =  "payload"
    case aps =  "aps"
    case body = "body"
    
    case version = "version"
    case deviceId = "device_id"
    case deviceType = "device_type"
    case userInstalledVersion = "user_installed_version"
    case currentLatestVersion = "current_latest_version"
    case updateRequired = "update_required"
    case criticalVersions = "critical_versions"
    case leastVersion = "least_version"
    case latestVersion = "latest_version"
    case isPortfolioLocked = "is_portfolio_locked"
    case totalAvailableCash = "total_available_cash"
    case cashChangeValue = "cash_change_value"
    case lockPortfolio = "lock_portfolio"
    case fractionalShares = "fractional_shares"
    case isMonthlyUpdateChecked = "is_monthly_update_checked"
    case isTrackRecordChecked = "is_track_record_checked"
    case stocksOwnedUser  = "stocks_owned_user"
    case stocksUpdated = "stocks_updated"
    case linkToken = "link_token"
    case publicToken = "public_token"
    case accessToken = "access_token"
    case isSupported = "is_supported"
    case isFromPlaid = "is_from_plaid"
    case plaidSecurityId = "plaid_security_id"
    case itemId = "item_id"
    
    case paveAllTimeMoneyReturn = "pave_all_time_money_return"
    case sp500AllTimeMoneyReturn = "sp500_all_time_money_return"
    case profitAboveSp500 = "profit_above_sp500"
    case paveReturnOnInvestment = "pave_return_on_investment"
    case annualizedPavePerformance = "annualized_pave_performance"
    case annualizedOutPerformance = "annualized_out_performance"
    case startDate = "start_date"
    case endDate = "end_date"
    case performanceGraph = "performance_graph"
    case sp500 = "sp500"
    case pave = "pave"
    case securityExclusions = "security_exclusions"
    case planSize = "plan_size"
    case overallPerformance = "overall_performance"
    case relativeRisk = "relative_risk"
    case returnPotential = "return_potential"
    case planStatistics = "plan_statistics"
    case riskScore = "risk_score"
    case returnScore = "return_score"
    case standardBenchmark = "standard_benchmark"
    case userBenchmark = "user_benchmark"
    case benchmark = "benchmark"
    
    
    
}
